-- Magnitude: Compare the measures values by categories. 
-- It helps us understand the importance of different categories
-- ∑ [measures] By [Dimension] . eg Total Sales By customer, total quantity by category etc

-- Find total customers by countries
SELECT
country,
COUNT(customer_key) AS total_customers
FROM Gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC
-- Find total customers by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM Gold.dim_customers
GROUP BY gender 
ORDER BY total_customers DESC
-- Find total products by category 
SELECT 
category,
COUNT(product_name) AS total_product
FROM Gold.dim_products
GROUP BY category
ORDER BY total_product DESC
-- What is the average costs in each category
SELECT 
category,
AVG(product_cost) AS avg_product_cost
FROM Gold.dim_products
GROUP BY category
ORDER BY avg_product_cost DESC
-- What is the total revenue generated for each category
SELECT 
p.category,
SUM(f.sales) AS total_revenue
FROM Gold.fact_sales f
LEFT JOIN Gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category 
ORDER BY total_revenue DESC
-- Find the total revenue generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales) AS total_revenue
FROM Gold.fact_sales f
LEFT JOIN Gold.dim_customers C
ON f.customer_key = c.customer_key
GROUP BY c.customer_key,c.first_name, c.last_name 
ORDER BY total_revenue DESC
-- What is distribution of sold items across countries
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM Gold.fact_sales f
LEFT JOIN Gold.dim_customers C
ON f.customer_key = c.customer_key
GROUP BY country
ORDER BY total_sold_items DESC